import { ImageResponse } from 'next/og';
// App router includes next/og by default

export const runtime = 'edge';

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);

    // ?savings=123&id=abc
    const savings = searchParams.get('savings');
    const id = searchParams.get('id');

    const hasSavings = savings && parseInt(savings) > 0;

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f8fafc',
            fontFamily: 'sans-serif',
          }}
        >
          {/* Logo / Branding */}
          <div
            style={{
              position: 'absolute',
              top: 40,
              left: 40,
              display: 'flex',
              alignItems: 'center',
              gap: 12,
            }}
          >
            <div
              style={{
                width: 40,
                height: 40,
                backgroundColor: '#09090b',
                borderRadius: 8,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: 'white',
                fontSize: 24,
                fontWeight: 'bold',
              }}
            >
              A
            </div>
            <div style={{ fontSize: 24, fontWeight: 'bold', color: '#09090b' }}>AudMint</div>
          </div>

          {/* Main Content */}
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              textAlign: 'center',
              padding: '0 80px',
            }}
          >
            <div
              style={{
                fontSize: 20,
                fontWeight: 700,
                color: '#64748b',
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                marginBottom: 16,
              }}
            >
              AI Infrastructure Audit
            </div>
            
            <h1
              style={{
                fontSize: 64,
                fontWeight: 800,
                color: '#09090b',
                margin: 0,
                lineHeight: 1.1,
                letterSpacing: '-0.02em',
              }}
            >
              {hasSavings 
                ? `Identified $${parseInt(savings).toLocaleString()} in Annual Savings`
                : 'My AI Infrastructure is Fully Optimized'}
            </h1>

            <div
              style={{
                marginTop: 40,
                padding: '12px 32px',
                backgroundColor: hasSavings ? '#16a34a' : '#09090b',
                color: 'white',
                borderRadius: 999,
                fontSize: 24,
                fontWeight: 600,
              }}
            >
              {hasSavings ? 'High ROI Opportunity' : 'Efficiency Verified'}
            </div>
          </div>

          {/* Footer */}
          <div
            style={{
              position: 'absolute',
              bottom: 40,
              display: 'flex',
              alignItems: 'center',
              color: '#64748b',
              fontSize: 18,
            }}
          >
            Generated by AudMint by Credex • audmint.credex.ai
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
      }
    );
  } catch (e: any) {
    console.log(`${e.message}`);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}
